namespace PaketLoadScripts

#load "D:\\code\\ShiningSword\\.paket\\load\\net471\\System.IO.fsx" 
#load "D:\\code\\ShiningSword\\.paket\\load\\net471\\System.Reflection.fsx" 
#load "D:\\code\\ShiningSword\\.paket\\load\\net471\\System.Resources.ResourceManager.fsx" 
#load "D:\\code\\ShiningSword\\.paket\\load\\net471\\System.Runtime.fsx" 
#load "D:\\code\\ShiningSword\\.paket\\load\\net471\\System.Runtime.Extensions.fsx" 
#load "D:\\code\\ShiningSword\\.paket\\load\\net471\\System.Runtime.Handles.fsx" 
#load "D:\\code\\ShiningSword\\.paket\\load\\net471\\System.Runtime.InteropServices.fsx" 
#load "D:\\code\\ShiningSword\\.paket\\load\\net471\\System.Security.Cryptography.Algorithms.fsx" 
#load "D:\\code\\ShiningSword\\.paket\\load\\net471\\System.Security.Cryptography.Encoding.fsx" 
#load "D:\\code\\ShiningSword\\.paket\\load\\net471\\System.Security.Cryptography.Primitives.fsx" 
#load "D:\\code\\ShiningSword\\.paket\\load\\net471\\System.Text.Encoding.fsx" 
#load "D:\\code\\ShiningSword\\.paket\\load\\net471\\System.Threading.fsx" 
#r "C:\\Users\\maxw\\.nuget\\packages\\system.security.cryptography.csp\\4.3.0\\lib\\net46\\System.Security.Cryptography.Csp.dll" 