namespace PaketLoadScripts

#load "D:\\code\\ShiningSword\\.paket\\load\\net471\\System.Collections.fsx" 
#load "D:\\code\\ShiningSword\\.paket\\load\\net471\\System.IO.fsx" 
#load "D:\\code\\ShiningSword\\.paket\\load\\net471\\System.Resources.ResourceManager.fsx" 
#load "D:\\code\\ShiningSword\\.paket\\load\\net471\\System.Runtime.fsx" 
#load "D:\\code\\ShiningSword\\.paket\\load\\net471\\System.Runtime.Extensions.fsx" 
#load "D:\\code\\ShiningSword\\.paket\\load\\net471\\System.Runtime.Handles.fsx" 
#load "D:\\code\\ShiningSword\\.paket\\load\\net471\\System.Runtime.InteropServices.fsx" 
#load "D:\\code\\ShiningSword\\.paket\\load\\net471\\System.Runtime.Numerics.fsx" 
#load "D:\\code\\ShiningSword\\.paket\\load\\net471\\System.Security.Cryptography.Algorithms.fsx" 
#load "D:\\code\\ShiningSword\\.paket\\load\\net471\\System.Security.Cryptography.Encoding.fsx" 
#load "D:\\code\\ShiningSword\\.paket\\load\\net471\\System.Security.Cryptography.Primitives.fsx" 
#load "D:\\code\\ShiningSword\\.paket\\load\\net471\\System.Text.Encoding.fsx" 
#r "C:\\Users\\maxw\\.nuget\\packages\\system.security.cryptography.openssl\\4.5.0\\lib\\netstandard2.0\\System.Security.Cryptography.OpenSsl.dll" 