namespace PaketLoadScripts

#load "D:\\code\\ShiningSword\\.paket\\load\\net452\\System.Collections.fsx" 
#load "D:\\code\\ShiningSword\\.paket\\load\\net452\\System.Diagnostics.Debug.fsx" 
#load "D:\\code\\ShiningSword\\.paket\\load\\net452\\System.Diagnostics.Tracing.fsx" 
#load "D:\\code\\ShiningSword\\.paket\\load\\net452\\System.Globalization.fsx" 
#load "D:\\code\\ShiningSword\\.paket\\load\\net452\\System.IO.fsx" 
#load "D:\\code\\ShiningSword\\.paket\\load\\net452\\System.Net.Http.fsx" 
#load "D:\\code\\ShiningSword\\.paket\\load\\net452\\System.Net.Primitives.fsx" 
#load "D:\\code\\ShiningSword\\.paket\\load\\net452\\System.Net.WebHeaderCollection.fsx" 
#load "D:\\code\\ShiningSword\\.paket\\load\\net452\\System.Resources.ResourceManager.fsx" 
#load "D:\\code\\ShiningSword\\.paket\\load\\net452\\System.Runtime.fsx" 
#load "D:\\code\\ShiningSword\\.paket\\load\\net452\\System.Threading.fsx" 
#load "D:\\code\\ShiningSword\\.paket\\load\\net452\\System.Threading.Tasks.fsx" 
#r "System" 